spring:
  profiles:
    active: local
    
  batch:
    job:
      names: ${job.name:NONE}
---
spring:
  profiles: local
  datasource:
    initialization-mode: embedded    url: jdbc:h2:tcp://localhost/~/batch
    username: sa
    password:
    driver-class-name: org.h2.Driver
    sql-script-encoding: UTF-8
    
logging:  level:
    root: trace